CC = gcc
CCWARNINGS = -Wall -Wextra -pedantic -Wmissing-prototypes -Wstrict-prototypes -Wredundant-decls -Wshadow
CFLAGS = -std=c17 -O3 -g3 $(CCWARNINGS)

all: 1 2

1: 1.c
	$(CC) 1.c -o 1 $(CFLAGS)

2: 2.c
	$(CC) 2.c -o 2 $(CFLAGS)